steps:
  # 1. Install Node modules
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Install Dependencies'
    args: ['install']

  # 2. Run the web build (Creates the deployable static files)
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Build Web Artifacts'
    args: ['run', 'build'] 
    env:
      # Inject the variable into the build environment using the secret values.
      # The value of the variable is set by the corresponding secret in the availableSecrets block.
      - 'EXPO_PUBLIC_FIREBASE_API_KEY=${EXPO_PUBLIC_FIREBASE_API_KEY}'
      - 'EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN=${EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN}'
      - 'EXPO_PUBLIC_FIREBASE_PROJECT_ID=${EXPO_PUBLIC_FIREBASE_PROJECT_ID}'
      - 'EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET=${EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET}'
      - 'EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}'
      - 'EXPO_PUBLIC_FIREBASE_APP_ID=${EXPO_PUBLIC_FIREBASE_APP_ID}'

  # 3. Deploy to Firebase Hosting
  - name: 'gcr.io/cloud-builders/firebase'
    id: 'Deploy to Hosting'
    args: ['deploy', '--project', '${PROJECT_ID}', '--only', 'hosting']

# Configuration to pull the secrets from Secret Manager
availableSecrets:
  secretManager:
  # Map the Secret Manager secret to a Cloud Build internal environment variable.
  # Since the names match, the mapping is simple and clear.
  - versionName: projects/${PROJECT_ID}/secrets/EXPO_PUBLIC_FIREBASE_API_KEY/versions/latest
    env: 'EXPO_PUBLIC_FIREBASE_API_KEY'
  - versionName: projects/${PROJECT_ID}/secrets/EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN/versions/latest
    env: 'EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN'
  - versionName: projects/${PROJECT_ID}/secrets/EXPO_PUBLIC_FIREBASE_PROJECT_ID/versions/latest
    env: 'EXPO_PUBLIC_FIREBASE_PROJECT_ID'
  - versionName: projects/${PROJECT_ID}/secrets/EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET/versions/latest
    env: 'EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET'
  - versionName: projects/${PROJECT_ID}/secrets/EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID/versions/latest
    env: 'EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID'
  - versionName: projects/${PROJECT_ID}/secrets/EXPO_PUBLIC_FIREBASE_APP_ID/versions/latest
    env: 'EXPO_PUBLIC_FIREBASE_APP_ID'